### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yudadabing** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#13]
Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22624.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\pythonw.exe
Node Path: 
Date: 03/31/2023 10:38:02
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\yudadabing\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 811
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Thanks for the feedback! Are you running the standalone version of Flow Launcher? And if so, how did you install the plugin?

**Comment by LLLLLC** [comment]
Tried two methods.
First method: installed according to the steps in README.md.
Second method: download the zip file from your repository and unzip it to C:\Users\myusername\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT
This error is reported for all.

**Comment by MichielvanBeers** [comment]
Allright, thanks for the input. I'll do some more research in that case.

**Comment by MichielvanBeers** [comment]
@yudadabing it looks like the 'cached_property' is not supported in Python 3.6, which you are using. Since the error is from a library I'm using and thus cannot directly control, could you upgrade to Python 3.8 or higher to see if that resolves the issue?

**Comment by MichielvanBeers** [comment]
Marking this issue as stale as there hasn't been any activity on this in a while. Please reopen if you need additional help. Thanks for your contribution!
