### ISSUE TITLE
Error when launch

### ISSUE THREAD

**Issue by Redbean3** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#16]
sorry reply to you so late, I left a message for you in the SSL error before, I just checked github and found that you updated 1.1.1 but the store did not. So I downloaded the zip file in release and unzip it in C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT. But when I try to use it, there is still an error, the log is as follows: 
```
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\[username]\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 04/02/2023 17:03:59
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: 

> C:\Users\[username]\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

It seems that I missed something?

**Comment by MichielvanBeers** [comment]
Hi,

No worries. I wanted to push out this fix anyway, since during testing I saw that this was fixing at least one bug. Maybe I was a bit expeditious with closing the issue, apologies for that.

With regard to the error you are seeing after installation: There is currently an issue that installing from the zip file doesn't work, but I'm not sure what is causing it. However, the update should be automatically added to the Plugin Store in a couple of hours. Could you check if it works correctly when that one is available? Thanks :)

**Comment by Redbean3** [comment]
Of course! Maybe I will try tomorrow and thank you for your patience and dedication.

**Comment by Redbean3** [comment]
hey, I'm glad to tell you the plugin downloaded from the store works without a hitch, although I still have connection issues but I think it's my personal network, the plugin itself should be fine. Thank you!

**Comment by MichielvanBeers** [comment]
Hi @Redbean3, that is great news, thanks for getting back to me :) I'll close this issue then, but don't hesitate to open a new one if it turns out that something else need fixing. Good luck!
