### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by matepak** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#18]
Every time I type a letter with Polish diacritics like 'ęóąśłżźćń', I get a UnicodeEncodeError.

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "D:\Users\mateusz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "D:\Users\mateusz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\lib\flox\__init__.py", line 132, in _query
    self.query(query)
  File "D:\Users\mateusz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\plugin\main.py", line 65, in query
    filename = self.save_conversation(
  File "D:\Users\mateusz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\plugin\main.py", line 168, in save_conversation
    file.write(new_content)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u015b' in position 28: character maps to <undefined>

```
</p>
</details>

**Comment by matepak** [comment]
Adding the parameter `encoding="utf-8"` to the open function within the `save_conversation` method fixed this error.

```python

with open(filename, "w", encoding="utf-8") as file:
                file.write(new_content)
```

**Comment by MichielvanBeers** [comment]
Thanks for the feedback! Will fix this in the next release.
