### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by xprssoul** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#20]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\beatz\AppData\Local\Programs\Python\Python311\Doc\html\index.html
Node Path: 
Date: 04/08/2023 22:10:40
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: An error occurred trying to start process 'C:\Users\beatz\AppData\Local\Programs\Python\Python311\Doc\html\index.html' with working directory 'C:\Users\beatz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1'. The specified executable is not a valid application for this OS platform.
 ---> System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\Users\beatz\AppData\Local\Programs\Python\Python311\Doc\html\index.html' with working directory 'C:\Users\beatz\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
@xprssoul it looks like your Python path is pointing towards the HTML documentation instead of the Python Executable: `Python Path: C:\Users\beatz\AppData\Local\Programs\Python\Python311\Doc\html\index.html`. If you configure the Python Path correctly, I expect it to work. Let me know if it fixes your issue!

**Comment by xprssoul** [comment]
Cool!
Thanks for your help!

**Comment by xprssoul** [comment]
It works!
