### ISSUE TITLE
Error Upon Launch 

### ISSUE THREAD

**Issue by fivves** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#24]
Please open new issue in: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/issues/new
1. upload log file: C:\Users\Eddie\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-04-16.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Eddie\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 04/16/2023 08:10:24
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Windows\system32

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\Eddie\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\lib\flox\__init__.py", line 47, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Windows\system32

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
@fivves thanks for the feedback! Some questions:

1. Are you running Flow Launcher in standalone mode?
2. Have you installed the plugin through the Plugin Store or manually?

**Comment by MichielvanBeers** [comment]
Marking this issue as stale as there hasn't been any activity on this in a while. Please reopen if you need additional help. Thanks for your contribution!
