### ISSUE TITLE
unable to use chatgpt in flow

### ISSUE THREAD

**Issue by amawdiin** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#32]
i get this error 

Please open new issue in: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/issues
1. upload log file: C:\Users\User\AppData\Roaming\FlowLauncher\Logs\1.15.0\2023-05-21.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 19044.2965
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 05/21/2023 12:41:17
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\lib\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn(

 ---> System.IO.InvalidDataException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\lib\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn(

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

my python path is `C:\Users\User\AppData\Local\Programs\Python\Python311\pythonw.exe`
python version is 3.11.2 
openai api key is in there

**Comment by amawdiin** [comment]
hope this gets solved, it would be so cool prompting chat gpt from everywhere within second

**Comment by MichielvanBeers** [comment]
Hi @amawdiin, it looks like there is some dependency issue. Could you see if the plugin runs successfully if you use the embed version of Python that comes with Flow Launcher? If can not find that, you can also install Python 3.8, 3.9 and 3.10 and set the location under Flow Launcher > Settings > Python Path

**Comment by Alexo88** [comment]
> Owner

works, thats it, im using 3.11, now i change for 3.10, and its working.

i hace installed both version years ago.

**Comment by amawdiin** [comment]
yes, i do have python and i do have the path in my flow launcher.

**Comment by MichielvanBeers** [comment]
Hmm, I'm a bit stuck on this one. I'm using `PythonEmbeddable-v3.11.4` myself and that works as expected. Could you do the following:

1. Reinstall the plugin to see if that fixes it.
2. Try using the PythonEmbeddable-v3.11.4 version (though I would be surprised if that solves the issue)
