### ISSUE TITLE
Plugin fail to load

### ISSUE THREAD

**Issue by AFaustini** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#36]
[2023-05-23.txt](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/files/11547436/2023-05-23.txt)

Flow Launcher version: 1.15.0
OS Version: 22621.1702
IntPtr Length: 8
x64: True

Python Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/23/2023 15:52:17
Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Programas\FlowLauncher\app-1.15.0\UserData\Logs\1.15.0'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 44
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 15
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 28
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Hi @AFaustini, it looks like Flow Launcher cannot find the general logging directory. I believe that this isn't related to my Plugin though. Can try reinstalling Flow Launcher to see if the issue is resvoled?

**Comment by AFaustini** [comment]
I am using portable version of Flow Launcher

**Comment by AFaustini** [comment]
Using installed version works well

**Comment by MichielvanBeers** [comment]
That is good news! Will that resolve your problem in that case?

**Comment by AFaustini** [comment]
No, because i use the portable version.

**Comment by AFaustini** [comment]
When i manually remove all plugin folders and reinstall the plugin, works again

**Comment by AFaustini** [comment]
When i manually remove all plugin folders and reinstall the plugin, works again

**Comment by MichielvanBeers** [comment]
Cool, thanks for the update!
