### ISSUE TITLE
ChatGPT Plugin Error

### ISSUE THREAD

**Issue by ghost** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#41]
Log File:

[2023-07-12.txt](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/files/12023817/2023-07-12.txt)

Exception Message:

Flow Launcher version: 1.16.0
OS Version: 19042.1706
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 07/12/2023 14:43:37
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
ModuleNotFoundError: No module named 'plugin'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
ModuleNotFoundError: No module named 'plugin'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Hi @TheAppleGuyGamz,

Thanks for the feedback. Can you check some things for me?
1. If you open the Plugin folder by going to Settings > Plugins > Clicking the folder icon next to the ChatGPT plugin > Open the folder called 'plugin', what do you see?
2. Can you try uninstalling and reinstalling the plugin to see if that resolves the issue?

Thanks!

**Comment by MichielvanBeers** [comment]
Closing this issue since it has been marked as stall. Please create a new issue if this is still a problem. Thank you for your contribution!
