### ISSUE TITLE
ChatGPT plugin failed to start

### ISSUE THREAD

**Issue by evetech2021** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#46]
[2023-09-11.txt](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/files/12575989/2023-09-11.txt)

Flow Launcher version: 1.16.1
OS Version: 23493.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\athar\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 09/11/2023 18:03:02
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Users\athar\AppData\Local\FlowLauncher\app-1.16.1

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\athar\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.1.1\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Users\athar\AppData\Local\FlowLauncher\app-1.16.1

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Hi @evetech2021, thanks for the info. I'm currently working on getting to the root issue of this. It seems that this might be related directly to my plugin, since there are also reports of other plugins having this issue (see [this issue ](https://github.com/Flow-Launcher/Flow.Launcher/issues/2299) on the Flow Launcher Github). I'll let you know when I have more info.

**Comment by guyman20** [comment]
@MichielvanBeers Any update on this issue?

**Comment by Garulf** [comment]
Hello,

Just wanted to chime in that this error may be due to my library Flox. Flox attempts to be compatible with Wox (old) *and* Flow Launcher (newer). To do this Flox looks for "Wox" or "FlowLauncher" (the default launcher folder names) to determine which launcher is running the plugin. Unfortunately this came with a lot of bugs as users can change this folder name.

Flox has been depreciated and replaced with https://github.com/Garulf/pyFlowLauncher. pyFLowLauncher is faster, has a better API, and has more features, with none of these bugs.

**Comment by MichielvanBeers** [comment]
Thanks for the additional info @Garulf. I'll put this on the backlog to implement.

@guyman20 do I understand correctly that you are still experiencing this issue?

**Comment by guyman20** [comment]
> Thanks for the additional info @Garulf. I'll put this on the backlog to implement.
> 
> @guyman20 do I understand correctly that you are still experiencing this issue?

Actually it works good for me now, thanks

**Comment by MichielvanBeers** [comment]
Thanks, I'll resolve this issue then an open a seperate one of migrating to the pay FlowLauncher plugin
