### ISSUE TITLE
ChatGPT: Failed to respond

### ISSUE THREAD

**Issue by Vintsu101** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#52]
[2024-02-10.txt](https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/files/14229366/2024-02-10.txt)

Flow Launcher version: 1.17.1
OS Version: 22631.3085
IntPtr Length: 8
x64: True

Python Path: C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 02/10/2024 16:23:09
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.2.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: ERROR:root:endswith first arg must be str or a tuple of str, not NoneType
Traceback (most recent call last):
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\lib\flox\__init__.py", line 132, in _query
    self.query(query)
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\plugin\main.py", line 56, in query
    if query.endswith(self.prompt_stop):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: endswith first arg must be str or a tuple of str, not NoneType

 ---> System.IO.InvalidDataException: ERROR:root:endswith first arg must be str or a tuple of str, not NoneType
Traceback (most recent call last):
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\lib\flox\__init__.py", line 132, in _query
    self.query(query)
  File "C:\Users\streetfashion\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.2.0\plugin\main.py", line 56, in query
    if query.endswith(self.prompt_stop):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: endswith first arg must be str or a tuple of str, not NoneType

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Looks like something is going wrong with the prompt stop. Could you share a screenshot of the settings you have entered?

**Comment by MichielvanBeers** [comment]
Closing this issue since it has been marked as stall. Please create a new issue if this is still a problem. Thank you for your contribution!
