### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by netlfm** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#6]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\flox\__init__.py", line 132, in _query
    self.query(query)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\plugin\main.py", line 99, in query
    answer = self.send_prompt(prompt, system_message)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\plugin\main.py", line 49, in send_prompt
    response = requests.request("POST", url, headers=headers, data=data)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\netlfm-work\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.0.3\lib\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

```
</p>
</details>

**Comment by MichielvanBeers** [comment]
Thanks for the feedback! Could you share with me the version of Python you are using? You can find this in Settings > General > Python Path. It should look something like: "Python Path: `C:\Users[username]\AppData\Local\Programs\Python\Python310\pythonw.exe`"

**Comment by Redbean3** [comment]
> Thanks for the feedback! Could you share with me the version of Python you are using? You can find this in Settings > General > Python Path. It should look something like: "Python Path: `C:\Users[username]\AppData\Local\Programs\Python\Python310\pythonw.exe`"

I got the similar error and the  Path is "C:\Users\[username]\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe" So is it because I'm using the wrong version of python?

**Comment by Redbean3** [comment]
> @Redbean3 thanks! @Redbean3 or @netlfm is one of you behind a proxy by any change?
yep, I set http server: 127.0.0.1 with port 4780
