### ISSUE TITLE
Timezone plugin bug

### ISSUE THREAD

**Issue by guyman20** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#60]
[2024-07-22.txt](https://github.com/user-attachments/files/16329224/2024-07-22.txt)

Flow Launcher version: 1.18.0
OS Version: 19045.4651
IntPtr Length: 8
x64: True

Python Path: C:\Python\Python37\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 07/22/2024 10:07:35
Exception:
Timezone Conversion Exception: 
Websites: https://github.com/Jwiggiff/Flow-Launcher-Timezone-Conversion-Plugin
Author: Josh Friedman
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56
        date = moment_timezone_1.default.tz(timestamp[0].date(), INPUT_TZ);
                                                         ^

TypeError: Cannot read property 'date' of undefined
    at Flow.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56:58)
    at Flow.run (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

 ---> System.IO.InvalidDataException: C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56
        date = moment_timezone_1.default.tz(timestamp[0].date(), INPUT_TZ);
                                                         ^

TypeError: Cannot read property 'date' of undefined
    at Flow.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:56:58)
    at Flow.run (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\lib\flow.js:147:75)
    at Object.<anonymous> (C:\Users\Guy\AppData\Roaming\FlowLauncher\Plugins\Timezone Conversion-1.1.0\dist\main.js:95:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mlazzarotto** [comment]
This is the repo for the ChatGPT plugin. You are in the wrong place.
