### ISSUE TITLE
failed to respond

### ISSUE THREAD

**Issue by rlodbrok** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#62]
Hi,
i have tried both project & personal API keys. I have a personal plan. no luck getting it working in flow launcher; works in powertoys but that is just a forward to the browser (no API key needed there).

details...

Please open new issue in: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/issues
1. upload log file: [2024-09-16.txt](https://github.com/user-attachments/files/17018261/2024-09-16.txt)
see attachement
3. copy below exception message

Flow Launcher version: 1.19.1
OS Version: 19045.4894
IntPtr Length: 8
x64: True

Python Path: C:\Users\Wim\AppData\Local\Programs\Python\Python37-32\pythonw.exe
Node Path: 
Date: 09/16/2024 21:16:52
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: MichielvanBeers
Version: 1.2.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\Wim\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\plugin\main.py", line 7, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\Wim\Documents\PortableApp\FlowLauncher\app-1.19.1\UserData\Plugins\ChatGPT-1.2.2\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\Wim\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 247
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Hi @rlodbrok, 

Thanks for the feedback! I see that you are using Python 3.7. If you upgrade to Python 3.8 or higher, I expect that this should work. Let me know if it works.

**Comment by MichielvanBeers** [comment]
Clossing this issue since there hasn't been a response in ~60 days
