### ISSUE TITLE
MissingSchema

### ISSUE THREAD

**Issue by skyd6ix** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#67]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\flox\__init__.py", line 132, in _query
    self.query(query)
    ~~~~~~~~~~^^^^^^^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\plugin\main.py", line 60, in query
    answer, prompt_timestamp, answer_timestamp = self.send_prompt(
                                                 ~~~~~~~~~~~~~~~~^
        prompt, system_message
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\plugin\main.py", line 125, in send_prompt
    response = requests.request(
        "POST", url, headers=headers, data=data, proxies=PROXIES
    )
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\requests\sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Skyd 6ix\AppData\Roaming\FlowLauncher\Plugins\ChatGPT-1.3.0\lib\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
    ...<2 lines>...
    )
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

```
</p>
</details>

**Comment by MichielvanBeers** [comment]
Hi @skyd6ix, looking at the error at the end of your message, it looks like something might be wrong with your URL. What URL did you provide?
