### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by clemens33** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#7]
I tried to run it using the portable version and got the following error. Seams like flow launcher has a problem detecting the directory when running as portable version.

```
Please open new issue in: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT/issues/new
1. upload log file: C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\UserData\Logs\1.14.0\2023-03-26.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 03/26/2023 18:01:07
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: Flow Launcher
Version: 1.0.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 5, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 5, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by MichielvanBeers** [comment]
Hi @clemens33, thanks for the feedback! It looks indeed like there are files missing.

I currently have some challenges still to reproduce the issue, since I cannot run the local version and the installed version next to each other. Could you share the content of this folder with me `C:\Users\ck\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\` ? Maybe I can see what is going wrong there.

**Comment by MichielvanBeers** [comment]
I just tried reproducing it by taking the steps below, but everything seems to work for me. Can you confirm that these are indeed the steps to reproduce?

1. Go to https://www.flowlauncher.com/
2. Click download
3. Click the 'Portable' version
4. Unpack and run
5. Install the ChatGPT plugin
6. Enter the API key
7. Perform a test search

**Comment by clemens33** [comment]
@MichielvanBeers Today on my work pc I tried to install it using the plugin store "pm install ..." - this worked! 

But installing manually (downloading zip file, manually extract it in the plugin folder etc.) as described in the README resulted in the mentioned issue on my home pc.

**Comment by MichielvanBeers** [comment]
@clemens33 ah that is good to know, I wasn't aware of that. I'll make sure to update the documentation to only reflect the installation through 'pm install'. Thanks!
