### ISSUE TITLE
new issue with ChatGPT plugin

### ISSUE THREAD

**Issue by EntonyHop** [MichielvanBeers/Flow.Launcher.Plugin.ChatGPT#8]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.23419.0
IntPtr Length: 8
x64: True

Python Path: C:\Apps\FlowLauncher\app-1.14.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 03/27/2023 12:17:10
Exception:
ChatGPT Exception: 
Websites: https://github.com/MichielvanBeers/Flow.Launcher.Plugin.ChatGPT
Author: Flow Launcher
Version: 1.0.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 5, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\main.py", line 11, in <module>
    from plugin.main import ChatGPT
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\plugin\main.py", line 5, in <module>
    from flox import Flox  # noqa: E402
  File "C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\flox\__init__.py", line 51, in <module>
    raise FileNotFoundError(LAUNCHER_NOT_FOUND_MSG)
FileNotFoundError: Unable to locate Launcher directory
Current working directory: C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MichielvanBeers** [comment]
Hi @EntonyHop, thanks for the feedback! This looks like a similar issue as #7. I just tried reproducing this by taking the following steps but was unsuccessful. 

1. Go to https://www.flowlauncher.com/
2. Click download
3. Click the 'Portable' version
4. Unpack and run
5. Install the ChatGPT plugin
6. Enter the API key
7. Perform a test search

Could you share the content of this folder `C:\Apps\FlowLauncher\app-1.14.0\Plugins\Flow.Launcher.Plugin.ChatGPT\lib\`? Maybe I can see which files are missing there. Thanks!

**Comment by EntonyHop** [comment]
I think the problem is that I have a portable version and it need Python, which is not automatically downloaded/install in Flow after clicking, or downloaded but the plugin does not see it. How to install portable version of Python for it?

**Comment by MichielvanBeers** [comment]
@EntonyHop your bug report does mention the Python version that is part of Flow Launcher (this one `Python Path: C:\Apps\FlowLauncher\app-1.14.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe`). Can you confirm that removing and reinstalling the Plugin to through the Plugin Store fixes the issue? Otherwise I'll do some additional really research. Thanks!

**Comment by MichielvanBeers** [comment]
Marking this issue as stale as there hasn't been any activity on this in a while. Please reopen if you need additional help. Thanks for your contribution!
